---
stages:
- name: PREPARE
  inputs:
  - type: git
    branch: master
    service: ${CC_REPO}
  triggers:
  - type: commit
  properties:
  - name: SCRIPT_DIR
    value: ${SCRIPT_DIR}
    type: text
  - name: SCRIPT_URL
    value: ${SCRIPT_URL}
    type: text
  jobs:
  - name: Prepare
    type: builder
    script: |-
      #!/bin/bash
      source <(curl -sSL "${SCRIPT_URL}/pipeline-PREPARE.sh")

      fetch_scripts "chaincode-pipeline/env.sh
      chaincode-pipeline/deploy-enterprise.sh
      chaincode-pipeline/install-go.sh
      chaincode-pipeline/download-fabric.sh
      chaincode-pipeline/build.sh
      chaincode-pipeline/unitest.sh"

      run_scripts "chaincode-pipeline/install-go.sh
      chaincode-pipeline/download-fabric.sh"
- name: BUILD
  inputs:
  - type: job
    stage: PREPARE
    job: Prepare
  triggers:
  - type: stage
  jobs:
  - name: Build Go Chaincode
    type: builder
    script: |-
      #!/bin/bash -x
      # script defined in chaincode project
      source ./scripts/build.sh
- name: UNITEST
  inputs:
  - type: job
    stage: BUILD
    job: Build Go Chaincode
  triggers:
  - type: stage
  jobs:
  - name: Unit Tests
    type: tester
    enable_tests: false
    script: |-
      #!/bin/bash -x
      # script defined in chaincode project
      source ./scripts/unitest.sh
- name: DEV-DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build Go Chaincode
  triggers:
  - type: stage
  properties:
  - name: UTILS_REPO_OWNER
    value: ${UTILS_REPO_OWNER}
    type: text
  - name: UTILS_REPO_NAME
    value: ${UTILS_REPO_NAME}
    type: text
  - name: ENV_REPO_OWNER
    value: ${ENV_REPO_OWNER}
    type: text
  - name: ENV_REPO_NAME
    value: ${ENV_REPO_NAME}
    type: text
  - name: BX_GIT_PAT
    value: ${BX_GIT_PAT}
    type: text
  jobs:
  - name: Chaincode Deploy
    type: builder
    script: |-
      #!/bin/bash -x
      # script defined in chaincode project
      source ./scripts/deploy-enterprise.sh  dev
- name: PROD-DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build Go Chaincode
  triggers:
  - type: stage
  properties:
  - name: UTILS_REPO_OWNER
    value: ${UTILS_REPO_OWNER}
    type: text
  - name: UTILS_REPO_NAME
    value: ${UTILS_REPO_NAME}
    type: text
  - name: ENV_REPO_OWNER
    value: ${ENV_REPO_OWNER}
    type: text
  - name: ENV_REPO_NAME
    value: ${ENV_REPO_NAME}
    type: text
  - name: BX_GIT_PAT
    value: ${BX_GIT_PAT}
    type: text
  jobs:
  - name: Chaincode Deploy
    type: builder
    script: |-
      #!/bin/bash -x
      # script defined in chaincode project
      source ./scripts/deploy-enterprise.sh  prod

