---
stages:
- name: PREPARE
  inputs:
  - type: git
    branch: master
    service: ${CC_REPO}
  triggers:
  - type: commit
  properties:
  - name: SCRIPT_DIR
    value: ${SCRIPT_DIR}
    type: text
  - name: SCRIPT_URL
    value: ${SCRIPT_URL}
    type: text
  jobs:
  - name: Prepare
    type: builder
    script: |-
      #!/bin/bash
      source <(curl -sSL "${SCRIPT_URL}/prepare-unstable.sh")
- name: BUILD
  inputs:
  - type: job
    stage: PREPARE
    job: Prepare
  triggers:
  - type: stage
  properties:
  - name: PLATFORM
    value: ${PLATFORM}
    type: text
  - name: SCRIPT_DIR
    value: ${SCRIPT_DIR}
    type: text 
  jobs:
  - name: Build Chaincode
    type: builder
    script: |-
      #!/bin/bash -x
      # script defined in chaincode project
      source "${SCRIPT_DIR}/router.sh" build "${PLATFORM}"
- name: TEST
  inputs:
  - type: job
    stage: BUILD
    job: Build Chaincode
  triggers:
  - type: stage
  properties:
  - name: PLATFORM
    value: ${PLATFORM}
    type: text
  - name: SCRIPT_DIR
    value: ${SCRIPT_DIR}
    type: text 
  jobs:
  - name: Test
    type: tester
    script: |-
      #!/bin/bash -x
      source "${SCRIPT_DIR}/router.sh" test "${PLATFORM}"
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build Chaincode
  triggers:
  - type: stage
  properties:
  - name: PLATFORM
    value: ${PLATFORM}
    type: text
  - name: SCRIPT_DIR
    value: ${SCRIPT_DIR}
    type: text 
  - name: BLOCKCHAIN_SERVICE_INSTANCE
    value: ${BLOCKCHAIN_SERVICE_INSTANCE}
    type: text 
  - name: CLOUDANT_SERVICE_INSTANCE
    value: ${CLOUDANT_SERVICE_INSTANCE}
    type: text 
  - name: REGION_ID
    value: ${REGION_ID}
    type: text 
  jobs:
  - name: Chaincode Deploy
    type: deployer
    target:
     region_id: ${REGION_ID}
     organization: ${ORG_NAME}
     space: ${SPACE_NAME}
     application: ${APP_NAME}
    script: |-
      #!/bin/bash -x
      source "${SCRIPT_DIR}/router.sh" deploy "${PLATFORM}"
    

