---
stages:
- name: PREPARE
  inputs:
  - type: git
    branch: master
    service: ${CC_REPO}
  triggers:
  - type: commit
  properties:
  - name: SCRIPT_DIR
    value: ${SCRIPT_DIR}
    type: text
  - name: SCRIPT_URL
    value: ${SCRIPT_URL}
    type: text
  jobs:
  - name: Prepare
    type: builder
    script: |-
      #!/bin/bash
      source <(curl -sSL "${SCRIPT_URL}/prepare-unstable.sh")
- name: BUILD
  inputs:
  - type: job
    stage: PREPARE
    job: Prepare
  triggers:
  - type: stage
  properties:
    name: PLATFORM
    value: ${PLATFORM}
    type: text
    name: SCRIPT_DIR
    value: ${SCRIPT_DIR}
    type: text 
  jobs:
  - name: Build Chaincode
    type: builder
    script: |-
      #!/bin/bash -x
      # script defined in chaincode project
      source ${SCRIPT_DIR}/router.sh build ${PLATFORM}
- name: TEST
  inputs:
  - type: job
    stage: BUILD
    job: Build Chaincode
  triggers:
  - type: stage
  properties:
    name: PLATFORM
    value: ${PLATFORM}
    type: text
    name: SCRIPT_DIR
    value: ${SCRIPT_DIR}
    type: text 
  jobs:
  - name: Unit Tests
    type: tester
    enable_tests: false
    script: |-
      #!/bin/bash -x
      source ${SCRIPT_DIR}/router.sh test ${PLATFORM}
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build Chaincode
  triggers:
  - type: stage
  properties:
    name: PLATFORM
    value: ${PLATFORM}
    type: text
    name: SCRIPT_DIR
    value: ${SCRIPT_DIR}
    type: text 
  jobs:
  - name: Chaincode Deploy
    type: builder
    script: |-
      #!/bin/bash -x
      source ${SCRIPT_DIR}/router.sh deploy ${PLATFORM}
    
- 
